<a href="https://colab.research.google.com/github/ekaratnida/Applied-machine-learning/blob/master/Naive%20Bayes%20Spam%20Email%20Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [167]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [168]:
spam_df=pd.read_csv('https://raw.githubusercontent.com/nikhilkr29/Email-Spam-Classifier-using-Naive-Bayes/refs/heads/main/emails.csv')

In [169]:
spam_df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [170]:
spam_df.head(10)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1
5  Subject: great nnews  hello , welcome to medzo...     1
6  Subject: here ' s a hot play in motion  homela...     1
7  Subject: save your money buy getting this thin...     1
8  Subject: undeliverable : home based business f...     1
9  Subject: save your money buy getting this thin...     1

In [171]:
spam_df.tail(10)

text  spam
5718  Subject: altos na gas model  kim , i know you ...     0
5719  Subject: power market research  i came across ...     0
5720  Subject: re : visit to houston  fyi  - - - - -...     0
5721  Subject: ees risk management presentations for...     0
5722  Subject: re : vacation  vince :  i just found ...     0
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

In [172]:
spam_df.describe()

spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [173]:
spam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


## Visualize the Data


In [174]:
spam_df.spam.value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

## Applying CountVectorizer to our Spam Ham Example

In [175]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, FeatureHasher
vectorizer= CountVectorizer() #FeatureHasher(n_features=1000) # TfidfVectorizer() #CountVectorizer()
spamham_countVectorizer=vectorizer.fit_transform(spam_df['text'])
spamham_countVectorizer.shape

(5728, 37303)

In [176]:
print(vectorizer.get_feature_names_out())
spamham_countVectorizer.toarray()

['00' '000' '0000' ... 'zzn' 'zzncacst' 'zzzz']


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Dividing the Cell for Training and Testing Prior to Training

In [177]:
X=spamham_countVectorizer
y=spam_df['spam']

In [178]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y, random_state=123)

In [179]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, ComplementNB

In [180]:
NB_classifier= MultinomialNB() #ComplementNB() # BernoulliNB() #MultinomialNB()
NB_classifier.fit(X_train,y_train)

MultinomialNB()

## Evaluating The Model

In [181]:
from sklearn.metrics import classification_report,confusion_matrix

In [182]:
y_predict_test=NB_classifier.predict(X_test)
y_predict_test

array([0, 0, 0, ..., 0, 0, 0])

In [183]:
cm=confusion_matrix(y_test,y_predict_test)
cm

array([[861,  11],
       [  1, 273]])

In [184]:
print(classification_report(y_test,y_predict_test))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       872
           1       0.96      1.00      0.98       274

    accuracy                           0.99      1146
   macro avg       0.98      0.99      0.99      1146
weighted avg       0.99      0.99      0.99      1146

